auths/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "auths"
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='car_rental:index'), name="logout"),
]

pro_ppw_ga/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_rental.urls')),
    path('auths/', include('auths.urls')),
    

    url(r'^oauth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auths/models.py
from django.db import models

# Create your models here.

auths/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = {
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user

auths/views.py
from django.shortcuts import render, redirect
from auths.forms import RegistrationForm
#from django.contrib.auth import authenticate, login


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('auths:login')
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})

'''
def authentication_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    
    if user is not None:
        request.session['user_login'] = username
        messages.success(request, "Login successful")
        print(username)
        res = HttpResponseRedirect(reverse('car_rental:index'))

        res.set_cookie('user_name', username)
        return res
    else:
        messages.error(request, "Account not found, please check your credentials")
        return HttpResponseRedirect(reverse('car_rental:index'))


def authentication_logout(request):
    request.session.flush()
    res = HttpResponseRedirect('/auths/login')
    res.delete_cookie('user_name')

    messages.info(request, "Logout successful, current session is successfully deleted")
    return HttpResponseRedirect(reverse('car_rental:login'))
    '''

auths/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!----------------------------------------------------------links------------------------------------------------------->
    <link href="https://fonts.googleapis.com/css?family=Muli:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Yeseva+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/d17701d3a2.js" crossorigin="anonymous"></script>
    
     <!--------------------------------------------------------------------------------------------------------------------->

    <title>Register Form</title>
</head>
<body>
    <!----------------------------------------------------------navigation bar------------------------------------------------------->

    <nav class="navbar navbar-expand-lg navbar-dark bg-none" id="mainNav">
        <a class="navbar-brand" href="#page-top"></a>
        <a class="navbar-brand" href="{% url 'car_rental:index' %}#welcome"><img src="{% static 'images/logo.png' %}" style="max-width: 200px;"></a>
        <button class="navbar-toggler navbar-toggler-right" style="background: #1A3852;" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>           
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link navbarfont" href="{% url 'car_rental:index' %}" style="padding: 10px;">HOME</a>
            </li>
        </ul>
        </div>
    </nav>
    
    <h1>Register New Account</h1>
    <br>
        <center>
        <form action="{% url 'auths:register' %}" method="POST" style="width: 50vw;">
            {% csrf_token %}
            <!---
            {{ form.username }}<br>
            {{ form.email }}<br>
            {{ form.first_name }}<br>
            {{ form.last_name}}<br>
            {{ form.password1 }}<br>
            {{ form.password2 }}<br>
            -->
            {{ form.non_field_errors }}
                <div class="fieldWrapper">
                    
                    <label for="{{ form.username.id_for_label }}">Username:</label><br>
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>
                <div class="fieldWrapper">
                    
                    <label for="{{ form.email.id_for_label }}">Your email:</label><br>
                    {{ form.email }}
                    {{ form.email.errors }}</p>
                </div>
                <div class="fieldWrapper">
                    
                    <label for="{{ form.first_name.id_for_label }}">Your First name:</label><br>
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </div>
                <div class="fieldWrapper">
                    
                    <label for="{{ form.last_name.id_for_label }}">Your Last name:</label><br>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </div>
                <div class="fieldWrapper">
                    <label for="{{ form.password1.id_for_label }}">Your Password:</label><br>
                    {{ form.password1 }}
                    {{ form.password1.errors }}
                </div>
                <div class="fieldWrapper">
                    <label for="{{ form.password2.id_for_label }}">Confirmation Password:</label><br>
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                </div>


            <br>
            <button type="submit" class="button btnClass2">Register</button>
        </form>
        </center>

    <!----------------------------------------------------------bootstrap script------------------------------------------------------->

    <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="/static/js/popper.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</body>
</html>