auths/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "auths"
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='car_rental:index'), name="logout"),
]

car_rental/urls.py
from django.urls import path
from . import views

app_name = 'car_rental'

urlpatterns = [
    path('', views.index, name='index'),
    path('car/', views.car, name='car'),
    path('addCar/', views.addCar, name='addCar'),
    path('transaction/', views.transaction, name='transaction'),
    path('article/', views.article, name='article'),
    path('addArticle/', views.addArticle, name='addArticle'),
    path('articleView/', views.articleView, name='articleView'),
    path('carSearchHomepage/', views.carSearchHomepage, name='carSearchHomepage'),
    path('update_rating/', views.update_rating, name='update_rating'),
    path('carSearch/', views.carSearch, name='carSearch'),
    path('viewCar/', views.viewCar, name='viewCar'),
    path('rentCar/', views.rentCar, name='rentCar'),
    path('favoriteCar/', views.favoriteCar, name='favoriteCar'),
    path('unfavoriteCar/', views.unfavoriteCar, name='unfavoriteCar'),
]

pro_ppw_ga/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_rental.urls')),
    path('auths/', include('auths.urls')),
    

    url(r'^oauth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rental/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

# Create your models here.

class Car(models.Model):
    car_name = models.CharField(max_length=30)
    user_name = models.CharField(max_length=30)
    year = models.CharField(max_length=4)
    city = models.CharField(max_length=30)
    price = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):
        return self.car_name

class FavoriteCar(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    person = models.ForeignKey(User, on_delete = models.CASCADE, primary_key = False)
    user = models.CharField(max_length=30)

class Transaction(models.Model):
    user_name = models.CharField(max_length=30)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    date = models.DateField(auto_now_add=True)

class Article(models.Model):
    title = models.CharField(max_length=30)
    date = models.DateField()
    short_desc = models.TextField()
    content = models.TextField()
    photo = models.ImageField(upload_to='images/', default= 'images/test.jpg')
    total_like = models.IntegerField(default=0)

    def __str__(self):
        return self.title

car_rental/forms.py
from django import forms
from django.forms import TextInput
from .models import *

class AddCarForm(forms.ModelForm): #TO DO
    
    class Meta:
        model = Car
        fields = [
            'car_name', 
            'user_name',
            'year',
            'city',
            'price',
            'description'
        ]
        labels = {
            'car_name': 'Car Name',
            'user_name': 'User Name',
            'year': 'Year',
            'city': 'City',
            'price': 'Price per Day',
            'description': 'Description'
        }
        widgets = {
            'car_name': forms.TextInput(attrs={'placeholder': 'Name of the car'}),
            'user_name': forms.TextInput(attrs={'placeholder': 'Your user name'}),
            'year': forms.TextInput(attrs={'placeholder': 'Manufacture year'}),
            'city': forms.TextInput(attrs={'placeholder': 'Location of the car'}),
            'price': forms.TextInput(attrs={'placeholder': 'Rate of rent per day'}),
            'description': forms.TextInput(attrs={'placeholder': 'Short description of your car'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class DateInput(forms.DateInput):
    input_type = 'date'

class RentCarForm(forms.ModelForm): #TO DO

    class Meta:
        model = Transaction
        fields = [
            'user_name',
            'car',
            'start_date',
            'end_date',
        ]
        labels = {
            'user_name': 'User Name',
            'car': 'Car',
            'start_date': 'Start Rent Date',
            'end_date': 'End Rent Date'
        }
        widgets = {
            'user_name': forms.TextInput(attrs={'placeholder': 'Your user name'}),
            'car': forms.Select(attrs={'class':'form-control'}),
            'start_date': DateInput(),
            'end_date': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class AddArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = [
            'title',
            'date',
            'short_desc',
            'content',
            'photo'

        ]
        labels = {
            'title': 'Title',
            'date': 'Date',
            'short_desc': 'Short Description',
            'content': 'Content',
            'photo' : 'Image'

        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title of the article'}),
            'date': DateInput(),
            'short_desc': forms.TextInput(attrs={'placeholder': 'Short description of the article'}),
            'content': forms.Textarea(attrs={'placeholder': 'Content of the article'}),
            'photo' : forms.FileInput(),

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

car_rental/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from .models import *
from . import forms
from .forms import AddCarForm, RentCarForm, AddArticleForm
import re
import json

counter = 0
id = 999999

# Create your views here.
def index(request):
    car = Car.objects.all()
    response = {'car' : car}
    return render(request, 'index.html', response)

def car(request):
    car = Car.objects.all()
    response = {'car' : car}
    return render(request, 'car.html', response)

def carSearchHomepage(request):
    search = request.POST['search']
    car = Car.objects.filter(car_name__icontains=search)
    if not car.exists():
        car = Car.objects.filter(price__range=(0,search))
    response = {'car' : car}
    return render(request, 'car.html', response)

def carSearch(request):
    search = request.POST['search']
    carTarget = Car.objects.filter(car_name__icontains=search)
    if not carTarget.exists():
        carTarget = Car.objects.filter(price__range=(0,search))
    response = []
    for car in carTarget:
        tempvar = {'car_name' : car.car_name, 'user_name' : car.user_name,  'city' : car.city,  'price' : car.price,'id' : car.id}
        response.append(tempvar)
    return JsonResponse(response, safe=False)

def viewCar(request):
    target_name = request.POST['car_name']
    target_user = request.POST['user_name']
    car = Car.objects.get(car_name=target_name, user_name=target_user)
    response = {'car' : car}
    return render(request, 'viewCar.html', response)

def addCar(request):
    if request.method == 'POST':
        form = forms.AddCarForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('car_rental:car')
    else:
        form = forms.AddCarForm()
        return render(request, 'addCar.html', {'form': form})

def rentCar(request):
    transaction = Transaction.objects.order_by('-date')
    if request.method == 'POST':
        form = forms.RentCarForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('../transaction')
    else:
        form = forms.RentCarForm()
    response = {'transaction': transaction, 'form': form, 'car': car}
    return render(request, 'rentCar.html', response)

def transaction(request):
    car = Car.objects.all()
    transaction = Transaction.objects.all().order_by('-date')
    response = {'car' : car, 'transaction': transaction}
    return render(request, 'transaction.html', response)

def article(request):
    artic = Article.objects.all()
    response = {'article': artic}
    return render(request, 'article.html', response)

def addArticle(request):
    if request.method == 'POST':
        form = forms.AddArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('car_rental:article')
    else:
        form = forms.AddArticleForm()
        return render(request, 'addArticle.html', {'form': form})

def articleView(request):
    arti_title = request.POST['title']
    articles = Article.objects.all()
    for article in articles:
        if arti_title == article.title:
            articleTarget = article
    response = {'article' : articleTarget}

    return render(request, 'articleView.html', response)

def update_rating(request):
    if request.method == 'GET':
        print('im here')
        print("REQUEST :",request.GET)
        titlestring = request.GET['title']

        article = Article.objects.get(title=titlestring) #getting the liked posts
        article.total_like += 1
        article.save()  # saving it to store in database
        return HttpResponse(article.total_like) # Sending an success response
    return HttpResponse("Request method is not a GET")


def favoriteCar(request):
    target_person = request.user
    if request.method == 'POST':
        target_user = request.POST['user_name']
        target_name = request.POST['car_name']
        target = Car.objects.get(car_name=target_name, user_name=target_user)
        if not FavoriteCar.objects.filter(car=target, person=target_person).exists():
            new = FavoriteCar()
            new.car = target
            new.person = target_person
            new.user = target_user
            new.save()
    favCars = FavoriteCar.objects.filter(person=target_person)
    carList = favCars.values_list('car')
    car = Car.objects.filter(id__in=carList)
    response = {'car' : car}
    return render(request, 'favoriteCar.html', response)
    
def unfavoriteCar(request):
    target_person = request.user
    if request.method == 'POST':
        target_user = request.POST['username']
        target_name = request.POST['carname']
        target_car = Car.objects.get(car_name=target_name, user_name=target_user)
        target = FavoriteCar.objects.get(person=target_person, car=target_car)
        target.delete()
    favCars = FavoriteCar.objects.filter(person=target_person)
    carList = favCars.values_list('car')
    car = Car.objects.filter(id__in=carList)
    response = {'car' : car}
    return render(request, 'favoriteCar.html', response)

car_rental/templates/addArticle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<body style="background-color: #E8E8E8;">
    <div class="container-fluid">
        <center><h1 class="title">ADD YOUR OWN ARTICLE!</h1></center>
    </div>

    <br>

    <div class="container" style="width: 60%; margin-bottom: 30px;">
        <form enctype="multipart/form-data" method="post" action="{% url 'car_rental:addArticle' %}">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-8" style="padding-left: 15px; padding-right: 15px; margin-left: auto; margin-right: auto; text-align: center;">
                    {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                    <br>
                    {% endfor %}
                </div>
            </div>
            <div class="form-row">
                <input type="submit" class="button btnClass2" value="Add">
            </div>
        </form>
    </div>
</body>


{% endblock %}

car_rental/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!----------------------------------------------------------links------------------------------------------------------->
    <link href="https://fonts.googleapis.com/css?family=Muli:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/d17701d3a2.js" crossorigin="anonymous"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
     <!--------------------------------------------------------------------------------------------------------------------->

    <title>RentACar</title>
</head>
<body>
    <!----------------------------------------------------------navigation bar------------------------------------------------------->

    <nav class="navbar navbar-expand-lg navbar-dark bg-none" id="mainNav">
        <a class="navbar-brand" href="#page-top"></a>
        <a class="navbar-brand" href="{% url 'car_rental:index' %}#welcome"><img src="{% static 'images/logo.png' %}" style="max-width: 200px;"></a>
        <button class="navbar-toggler navbar-toggler-right" style="background: #1A3852;" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>           
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link navbarfont" href="{% url 'car_rental:index' %}" style="padding: 10px;">HOME</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle navbarfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding: 10px;">
                    CARS
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item navbarfont" href="{% url 'car_rental:car' %}" style="margin: 0;">CARS AVAILABLE</a>
                    <a class="dropdown-item navbarfont" href="{% url 'car_rental:addCar' %}" style="margin: 0;">REGISTER YOUR CAR!</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link navbarfont" href="{% url 'car_rental:transaction' %}" style="padding: 10px;">TRANSACTION</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbarfont" href="{% url 'car_rental:article' %}" style="padding: 10px;">ARTICLES</a>
            </li>
            {%if user.is_authenticated%}
                <li class="nav-item">
                    <a class="nav-link navbarfont" href="{% url 'car_rental:favoriteCar'%}" style="padding: 10px;">FAVORITE CARS</a>
                </li>
            {%endif%}
            {%if user.is_authenticated%}
                <li class="nav-item">
                    <a class="nav-link navbarfont" href="{%url 'auths:logout'%}" style="padding: 10px;">LOG OUT</a>
                </li>
            {%endif%}
        </ul>
        </div>
    </nav>


    {% block content %}
    
    {% endblock %}

    <!----------------------------------------------------------bootstrap script------------------------------------------------------->

    
    <!-- <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="/static/js/popper.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"   integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="   crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/carSearch.js' %}"></script>

</body>
</html>

car_rental/templates/car.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<title>Cars | RentACar</title>

<body style="background: #E8E8E8;">
    {%if user.is_authenticated%}
        <div class="container">
            <div class="row">
                <div class="col-sm-8"></div>
                
                <!-- <div class="col-sm">
                    <div class="select-box"><select id="selectSearch">search by: 
                            <option id="name" value="name">Name</option> 
                            <option id="price" value="price">Price</option> 
                        </select>                
                    </div>
                </div> -->
                <div class="col-sm">
                    <h5>
                        <form class="example" method="POST" action="{% url 'car_rental:car' %}">
                            {% csrf_token %}
                            <input class="form-example" id="search" type="search" placeholder="Search by name or price..." name="search">
                            <!-- <button type="submit"><i class="fa fa-search" style="border-radius: 20px;max-width: 10px;"></i></button> -->
                        </form>
                    </h5>
                </div>
            </div>
        </div>
            
        <br>
        <div class="container-fluid" style="margin: 0;"><h1 class="title">CARS</h1></div>

        <center><div class="container" style="margin: 0;">
            <div class="d-flex flex-wrap justify-content-center carDisplay">
            {% for car in car %}
            <form action="{% url 'car_rental:viewCar' %}" method="POST">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body text-center">
                        <img src="{% static 'images/car.png' %}" class="pict">
                        <h5 class="card-title">{{ car.car_name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted" style="margin-bottom: 4px;">{{ car.city }}</h6>
                        <p class="card-text" style="margin-bottom: 8px;">Rp. {{ car.price }},00 / day</p>
                        <input type='hidden' name='car_name' value='{{ car.car_name }}'>
                        <input type="hidden" name="user_name" value="{{ car.user_name }}">
                        <input type="submit" class="button btnClass" value='View Details'>
                    </div>
                </div>
            </form>
            {% endfor %}
            </div>
        </div></center>
    {%else%}
        <div class="container" style="margin-top: 10vh;">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <br><br><br>
                    <center>
                        <h2>Welcome to RentACar!</h2>
                        <p>Please <a href="{%url 'auths:login'%}">log in</a> to continue..</p>
                    </center>
                </div>
            </div>
        </div>
    {%endif%}

    <script>
        $('#search').on("keyup", function() {  
        $.ajax({
            url: `/carSearch/`,
            data: { "search": $(this).val().toLowerCase()},
            dataType: 'json',
            success: function (data) {
                $(".carDisplay").html(data.map(car =>
                    `<div class="card">
                        <div class="card-body text-center">
                            <img src="https://pbs.twimg.com/media/EXpGD2hVcAEnABZ?format=png&name=small" class="pict">
                            <h5 class="card-title">${car.car_name }</h5>
                            <h6 class="card-subtitle mb-2 text-muted" style="margin-bottom: 4px;">${car.city}</h6>
                            <p class="card-text" style="margin-bottom: 8px;">Rp. ${car.price},00 / day</p>
                            <input type='hidden' name='car_name' value='${car.car_name}'>
                            <input type='hidden' name='user_name' value='${car.user_name}'>
                            <input type="submit" class="button btnClass" value='View Details'>
                        </div>
                    </div>`
                ))
            }
        })    
    });
    </script>
</body>


{% endblock %}

car_rental/templates/favoriteCar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body style="background: #E8E8E8;">
    {%if user.is_authenticated%}
        <div class="container">
            <div class="row">
                <div class="col-sm-8"></div>
                <div class="col-sm">
                    <form class="example" method="POST" action="{% url 'car_rental:carSearchHomepage' %}">
                        {% csrf_token %}
                        <input class="form.example" type="search" placeholder="Search a Car..." name="search">
                        <button type="submit"><i class="fa fa-search" style="border-radius: 20px;max-width: 10px;"></i></button>
                    </form>
                </div>
            </div>
        </div>
        <br>
        <div class="container-fluid"><h1 class="title">FAVORITE CARS</h1></div>

        <div class="container" style="margin: 0;">
            <div class="d-flex flex-wrap justify-content-center">
            {% for car in car %}
            
            
            <div class="card">
                <div class="card-body text-center">
                    <img src="{% static 'images/car.png' %}" class="pict">
                    <h5 class="card-title">{{ car.car_name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ car.city }}</h6>
                    <p class="card-text">{{ car.price }} / day</p>
                    <div class="row">
                        <div class="col-md">
                            <form action="{% url 'car_rental:viewCar' %}" method="POST">
                                {% csrf_token %}
                                <input type='hidden' name='car_name' value='{{ car.car_name }}'>
                                <input type='hidden' name='user_name' value='{{ car.user_name }}'>
                                <input type="submit" class="button btnClass" style="width: fit-content;" value='View Details'>
                            </form>
                        </div>
                        <div class="col-md">
                            <form action="{% url 'car_rental:unfavoriteCar'%}" method="POST">
                                {% csrf_token %}
                                <input type='hidden' name='carname' value='{{ car.car_name }}'>
                                <input type='hidden' name='username' value='{{ car.user_name }}'>
                                <input type="submit" class="button btnClass" value='Remove'>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
            </div>
        </div>
    {%else%}
        <div class="container" style="margin-top: 10vh;">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <br><br><br>
                    <center>
                        <h2>Welcome to RentACar!</h2>
                        <p>Please <a href="{%url 'auths:login'%}">log in</a> to continue..</p>
                    </center>
                </div>
            </div>
        </div>
    {%endif%}
</body>

{% endblock %}

car_rental/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<title>RentACar!</title>

<body id="home">
    {%if user.is_authenticated%}
        <div class="container" style="margin-top: 10vh;">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <br><br><br>
                    <center><h2 id="welcome">Welcome, <br>{{user.first_name}} {{user.last_name}}</h2></center>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <form class="form-inline my-2 my-lg-0 example" method="POST" action="{% url 'car_rental:carSearchHomepage' %}">
                        {% csrf_token %}
                        <input type="form-control mr-sm-2" placeholder="Search a Car..." name="search">
                        <button type="submit"><i class="fa fa-search" style="border-radius: 20px;max-width: 10px;"></i></button>
                    </form>
                </div>
            </div>
        </div>
    {%else%}
        <div class="container" style="margin-top: 10vh;">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <br><br><br>
                    <center>
                        <h2>Welcome to RentACar!</h2>
                        <p>Please <a href="{%url 'auths:login'%}">log in</a> to continue..</p>
                    </center>
                </div>
            </div>
        </div>
    {%endif%}

</body>

{% endblock %}

car_rental/templates/rentCar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body style="background-color: #E8E8E8;">
    {%if user.is_authenticated%}
        <div class="container-fluid title"><h1>RENT FORM</h1></div> <br><br>

        <br><br>

        <div class="container">
            <form method="post" action="{% url 'car_rental:rentCar' %}">
                {% csrf_token %}

                <div class="form-row">
                    <div class="form-group col-sm-8" style="padding-left: 15px; padding-right: 15px; margin-left: auto; margin-right: auto; text-align: center;">
                        {% for fields in form %}
                            {{ fields.label_tag }}
                            <br>
                            {{ fields }}
                            <br>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-row">
                    <input type="submit" class="button btnClass" value="SUBMIT">
                </div>
            </form>
        </div>
    {%else%}
        <div class="container" style="margin-top: 10vh;">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <br><br><br>
                    <center>
                        <h2>Welcome to RentACar!</h2>
                        <p>Please <a href="{%url 'auths:login'%}">log in</a> to continue..</p>
                    </center>
                </div>
            </div>
        </div>
    {%endif%}
</body>

{% endblock %}

car_rental/templates/viewCar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body style="background: #E8E8E8;">
    {%if user.is_authenticated%}
        <center><div class="container_fluid"><div class="header-line"></div></div></center>
        <div class="container" style="margin-bottom:30px;">
            <center>
                <br>
                <img src="{% static 'images/car.png' %}" class="pict" style="max-width: 200px;">
                <h2 class="review" id="carname">{{ car.car_name }}</h2>
                <p class="review">{{ car.user_name }} </p>
                <h4 class="review">{{ car.city }}  {{ car.year }}</h4>
                <h4 class="review">Rp. {{ car.price }},00 / day</h4>
                <p class="review">{{ car.description }}</p><br><br>
                <div class="container" style="width: 25vw;">
                    <div class="row">
                        <div class = "col-md">
                            <form method="POST" action="{% url 'car_rental:rentCar' %}">
                                {% csrf_token %}
                                <input class="button btnClass2" type="submit" value="Rent now!">
                            </form>
                        </div>
                        <div class="col-md">
                            <form method="POST" action="{% url 'car_rental:favoriteCar' %}">
                                {% csrf_token %}
                                <input type='hidden' name='car_name' value='{{ car.car_name }}'>
                                <input type='hidden' name='user_name' value='{{ car.user_name }}'>
                                <input class="button btnClass2" style="width:fit-content" type="submit" value="Add to favorites">
                            </form>
                        </div>
                    </div>
                </div>
            </center>
        </div>
    {%else%}
        <div class="container" style="margin-top: 10vh;">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <br><br><br>
                    <center>
                        <h2>Welcome to RentACar!</h2>
                        <p>Please <a href="{%url 'auths:login'%}">log in</a> to continue..</p>
                    </center>
                </div>
            </div>
        </div>
    {%endif%}
</body>

{% endblock %}